### ISSUE TITLE
Error when deploying with Vercel

### ISSUE THREAD

**Issue by IzMichael** [steven-tey/dub#118]
Hiya, I'm attempting to deploy my own instance with the provided 'Deploy with Vercel' button, but after entering my environment variables, it's just returning an error of `Invalid request: should be object.`.

I've followed the instructions from the `.env.example` and my Planetscale SQL tables are setup using the `prisma/schema.prisma`.
![image](https://user-images.githubusercontent.com/57115702/202686546-8220c084-3f54-4708-bb9a-f17b4b1d987c.png)

Thanks!

**Comment by IzMichael** [comment]
I've just tried again (from scratch) and there's been no issue. Guess this was a fluke?

**Comment by IzMichael** [comment]
Oops, I'm back with a different error now lol. It's having an issue installing the packages. I think it's failing with the node version that Vercel is using?


```
[21:52:38.213] Cloning github.com/IzMichael/IzDub (Branch: main, Commit: 85282f1)
[21:52:38.461] Previous build cache not available
[21:52:39.010] Cloning completed: 796.4ms
[21:52:39.458] Running "vercel build"
[21:52:39.951] Vercel CLI 28.5.5
[21:52:40.276] Installing dependencies...
[21:52:40.632] yarn install v1.22.17
[21:52:40.708] [1/4] Resolving packages...
[21:52:41.034] [2/4] Fetching packages...
[21:52:56.498] error openid-client@5.1.9: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.12.1"
[21:52:56.510] error Found incompatible module.
[21:52:56.510] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[21:52:56.551] Error: Command "yarn install" exited with 1
```

![image](https://user-images.githubusercontent.com/57115702/202843271-df1f4f81-3b76-4c86-9b62-8f0e0e191c0d.png)

**Comment by IzMichael** [comment]
Update: I've found where to change my node version in vercel, but now it's failing to prerender something...

```
[22:03:31.702] info  - Compiled successfully
[22:03:31.702] info  - Collecting page data...
[22:03:36.183] info  - Generating static pages (0/18)
[22:03:36.285] info  - Generating static pages (4/18)
[22:03:36.299] info  - Generating static pages (8/18)
[22:03:36.319] info  - Generating static pages (13/18)
[22:03:37.706] 
[22:03:37.706] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[22:03:37.706] TypeError: Cannot read properties of undefined (reading 'entities')
[22:03:37.707]     at getExternalUrls (/vercel/path0/.next/server/pages/index.js:2129:36)
[22:03:37.707]     at getTweet (/vercel/path0/.next/server/pages/index.js:2142:23)
[22:03:37.707]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[22:03:37.707]     at async Promise.all (index 6)
[22:03:37.707]     at async getStaticProps (/vercel/path0/.next/server/pages/index.js:2289:20)
[22:03:37.707]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:384:20)
[22:03:37.707]     at async /vercel/path0/node_modules/next/dist/export/worker.js:248:32
[22:03:37.707]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[22:03:37.707] info  - Generating static pages (18/18)
[22:03:37.710] 
[22:03:37.710] > Build error occurred
[22:03:37.712] Error: Export encountered errors on following paths:
[22:03:37.712] 	/
[22:03:37.712]     at /vercel/path0/node_modules/next/dist/export/index.js:408:19
[22:03:37.712]     at runMicrotasks (<anonymous>)
[22:03:37.712]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[22:03:37.713]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[22:03:37.713]     at async /vercel/path0/node_modules/next/dist/build/index.js:1331:21
[22:03:37.713]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[22:03:37.713]     at async /vercel/path0/node_modules/next/dist/build/index.js:1191:17
[22:03:37.713]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[22:03:37.713]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:65:29)
[22:03:37.764] error Command failed with exit code 1.
[22:03:37.764] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[22:03:37.780] Error: Command "yarn run build" exited with 1
```

Any ideas?

**Comment by PatelN123** [comment]
I get this same issue. 

```
TypeError: Cannot read properties of undefined (reading 'entities')```

**Comment by steven-tey** [comment]
Ahh that's something to do with the [`getTweets` function](https://github.com/steven-tey/dub/blob/main/lib/twitter/get-tweet.ts) – feel free to get rid of that since that's not really needed for the link shortener.

I'm making a note to fix this bug in the code, thanks for reporting!

**Comment by steven-tey** [comment]
@IzMichael @PatelN123 Ahh that's something to do with the [`getTweets` function](https://github.com/steven-tey/dub/blob/main/lib/twitter/get-tweet.ts) – feel free to get rid of that since that's not really needed for the link shortener.

I'm making a note to fix this bug in the code, thanks for reporting!

**Comment by IzMichael** [comment]
@morandalex A temp(?) fix would be to use node 16, instead of 18
