### ISSUE TITLE
Prisma fails

### ISSUE THREAD

**Issue by skybird-dev** [steven-tey/dub#128]
I use mysql on rails app.

[22:13:02.160] [4/4] Building fresh packages...
[22:13:09.963] $ prisma generate || true
[22:13:11.500] Prisma schema loaded from prisma/schema.prisma
[22:13:12.969] 
[22:13:12.970] ✔ Generated Prisma Client (4.6.1 | library) to ./shared/prisma-client in 276ms
[22:13:12.970] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[22:13:12.970] ```
[22:13:12.971] import { PrismaClient } from './shared/prisma-client'
[22:13:12.971] const prisma = new PrismaClient()
[22:13:12.971] ```
[22:13:13.021] Done in 64.28s.
[22:13:13.060] Detected Next.js version: 13.0.5
[22:13:13.063] Running "yarn run build"
[22:13:13.410] yarn run v1.22.17
[22:13:13.456] $ prisma generate
[22:13:15.006] Prisma schema loaded from prisma/schema.prisma
[22:13:16.479] 
[22:13:16.479] ✔ Generated Prisma Client (4.6.1 | library) to ./shared/prisma-client in 274ms
[22:13:16.480] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[22:13:16.480] ```
[22:13:16.480] import { PrismaClient } from './shared/prisma-client'
[22:13:16.481] const prisma = new PrismaClient()
[22:13:16.481] ```
[22:13:17.898] $ next build]
[22:13:18.621] info  - Checking validity of types...
[22:13:30.870] info  - Creating an optimized production build...
[22:13:30.937] warn  - You are using an experimental edge runtime, the API might change.
[22:13:33.219] warn  - The @next/font/google font Inter has no selected subsets. Please specify subsets in the function call or in your next.config.js, otherwise no fonts will be preloaded. Read more: https://nextjs.org/docs/messages/google-fonts-missing-subsets
[22:14:16.602] warn  - Compiled with warnings
[22:14:16.603] 
[22:14:16.603] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[22:14:16.603] A Node.js API is used (process.version at line: 26) which is not supported in the Edge Runtime.
[22:14:16.603] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[22:14:16.604] 
[22:14:16.604] Import trace for requested module:
[22:14:16.604] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[22:14:16.604] ./lib/upstash.ts
[22:14:16.604] 
[22:14:16.605] info  - Collecting page data...
[22:14:17.286] Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
[22:14:17.287] In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
[22:14:17.287]     at new PrismaClient (/vercel/path0/node_modules/.prisma/client/index.js:3:11)
[22:14:17.288]     at 9744 (/vercel/path0/.next/server/pages/_proxy/[domain]/[key].js:21:33)
[22:14:17.288]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[22:14:17.289]     at /vercel/path0/.next/server/pages/_proxy/[domain]/[key].js:45:69
[22:14:17.289]     at __webpack_require__.a (/vercel/path0/.next/server/webpack-runtime.js:89:13)
[22:14:17.290]     at 938 (/vercel/path0/.next/server/pages/_proxy/[domain]/[key].js:31:21)
[22:14:17.290]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[22:14:17.291]     at __webpack_exec__ (/vercel/path0/.next/server/pages/_proxy/[domain]/[key].js:294:39)
[22:14:17.291]     at /vercel/path0/.next/server/pages/_proxy/[domain]/[key].js:295:77
[22:14:17.292]     at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:177:21)
[22:14:17.295] 
[22:14:17.296] > Build error occurred
[22:14:17.301] Error: Failed to collect page data for /_proxy/[domain]/[key]
[22:14:17.302]     at /vercel/path0/node_modules/next/dist/build/utils.js:959:15
[22:14:17.302]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[22:14:17.302]   type: 'Error'
[22:14:17.303] }
[22:14:17.401] error Command failed with exit code 1.
[22:14:17.402] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[22:14:17.440] Error: Command "yarn run build" exited with 1

**Comment by minhpn76** [comment]
Please make sure your application is connected to the database.
My way is:

1. Create MySQL database by docker (follow docker-compose MySQL)
2. Create .env reference .env.example and replace the DATBASE_URL you had
3. Run `npx prisma migrate dev `and then `yarn dev || yarn start `whatever you need.
