### ISSUE TITLE
Error while deploying on Vercel

### ISSUE THREAD

**Issue by masteradit** [steven-tey/dub#132]
Here are the build logs:
```
[08:57:12.420] Cloning github.com/masteradit/dub (Branch: main, Commit: c366ff2)
[08:57:12.426] Skipping build cache since Vercel CLI used --force option
[08:57:13.041] Cloning completed: 620.2ms
[08:57:13.464] Running "vercel build"
[08:57:13.962] Vercel CLI 28.5.6
[08:57:14.282] Installing dependencies...
[08:57:14.645] yarn install v1.22.17
[08:57:14.725] [1/4] Resolving packages...
[08:57:15.001] [2/4] Fetching packages...
[08:57:36.298] [3/4] Linking dependencies...
[08:57:36.311] warning " > focus-trap-react@10.0.1" has unmet peer dependency "prop-types@^15.8.1".
[08:57:36.312] warning "mailing-core > mjml-react > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".
[08:57:36.313] warning "react-hot-toast > goober@2.1.11" has unmet peer dependency "csstype@^3.0.10".
[08:57:36.314] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "konva@>=2.6".
[08:57:36.314] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "react-konva@^16.8.0 || ^17.0.0".
[08:57:36.315] warning "react-spring > @react-spring/native@9.5.5" has unmet peer dependency "react-native@>=0.58".
[08:57:36.315] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "@react-three/fiber@>=6.0".
[08:57:36.315] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "three@>=0.126".
[08:57:36.315] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "react-zdog@>=1.0".
[08:57:36.315] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "zdog@>=1.0".
[08:57:36.316] warning " > @trivago/prettier-plugin-sort-imports@4.0.0" has unmet peer dependency "@vue/compiler-sfc@3.x".
[08:57:36.341] warning Workspaces can only be enabled in private projects.
[08:57:50.863] [4/4] Building fresh packages...
[08:57:56.513] $ prisma generate || true
[08:57:57.714] Prisma schema loaded from prisma/schema.prisma
[08:57:58.931] 
[08:57:58.931] ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 193ms
[08:57:58.931] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[08:57:58.931] ```
[08:57:58.931] import { PrismaClient } from '@prisma/client'
[08:57:58.931] const prisma = new PrismaClient()
[08:57:58.931] ```
[08:57:58.973] Done in 44.33s.
[08:57:59.087] Detected Next.js version: 13.0.5
[08:57:59.088] Running "yarn run build"
[08:57:59.357] yarn run v1.22.17
[08:57:59.388] $ prisma generate
[08:58:00.605] Prisma schema loaded from prisma/schema.prisma
[08:58:01.816] 
[08:58:01.819] ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 199ms
[08:58:01.819] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[08:58:01.819] ```
[08:58:01.819] import { PrismaClient } from '@prisma/client'
[08:58:01.819] const prisma = new PrismaClient()
[08:58:01.819] ```
[08:58:01.916] $ next build
[08:58:02.381] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[08:58:02.382] This information is used to shape Next.js' roadmap and prioritize features.
[08:58:02.382] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[08:58:02.382] https://nextjs.org/telemetry
[08:58:02.382] 
[08:58:02.509] info  - Linting and checking validity of types...
[08:58:11.711] info  - Creating an optimized production build...
[08:58:11.765] warn  - You are using an experimental edge runtime, the API might change.
[08:58:36.220] warn  - Compiled with warnings
[08:58:36.220] 
[08:58:36.221] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[08:58:36.221] A Node.js API is used (process.version at line: 26) which is not supported in the Edge Runtime.
[08:58:36.221] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[08:58:36.221] 
[08:58:36.221] Import trace for requested module:
[08:58:36.221] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[08:58:36.221] ./lib/upstash.ts
[08:58:36.221] 
[08:58:36.222] info  - Collecting page data...
[08:58:41.740] info  - Generating static pages (0/19)
[08:58:41.860] info  - Generating static pages (4/19)
[08:58:41.876] info  - Generating static pages (9/19)
[08:58:41.921] info  - Generating static pages (14/19)
[08:58:41.956] (node:1163) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
[08:58:41.956] (Use `node --trace-warnings ...` to show where the warning was created)
[08:58:42.049] 
[08:58:42.050] Error occurred prerendering page "/metatags". Read more: https://nextjs.org/docs/messages/prerender-error
[08:58:42.050] TypeError: Cannot read properties of undefined (reading 'entities')
[08:58:42.051]     at getExternalUrls (/vercel/path0/.next/server/chunks/5298.js:491:36)
[08:58:42.051]     at getTweet (/vercel/path0/.next/server/chunks/5298.js:504:23)
[08:58:42.051]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[08:58:42.051]     at async Promise.all (index 0)
[08:58:42.051]     at async getStaticProps (/vercel/path0/.next/server/pages/metatags.js:274:20)
[08:58:42.051]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:384:20)
[08:58:42.051]     at async /vercel/path0/node_modules/next/dist/export/worker.js:248:32
[08:58:42.052]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[08:58:42.182] (node:1169) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
[08:58:42.183] (Use `node --trace-warnings ...` to show where the warning was created)
[08:58:42.374] 
[08:58:42.374] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[08:58:42.374] TypeError: Cannot read properties of undefined (reading 'entities')
[08:58:42.378]     at getExternalUrls (/vercel/path0/.next/server/chunks/5298.js:491:36)
[08:58:42.378]     at getTweet (/vercel/path0/.next/server/chunks/5298.js:504:23)
[08:58:42.378]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[08:58:42.378]     at async Promise.all (index 4)
[08:58:42.378]     at async getStaticProps (/vercel/path0/.next/server/pages/index.js:1800:20)
[08:58:42.378]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:384:20)
[08:58:42.378]     at async /vercel/path0/node_modules/next/dist/export/worker.js:248:32
[08:58:42.379]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[08:58:42.379] 
[08:58:42.379] > Build error occurred
[08:58:42.379] Error: Export encountered errors on following paths:
[08:58:42.379] 	/
[08:58:42.379] 	/metatags
[08:58:42.379]     at /vercel/path0/node_modules/next/dist/export/index.js:408:19
[08:58:42.380]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[08:58:42.380]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[08:58:42.380]     at async /vercel/path0/node_modules/next/dist/build/index.js:1334:21
[08:58:42.380]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[08:58:42.380]     at async /vercel/path0/node_modules/next/dist/build/index.js:1194:17
[08:58:42.380]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[08:58:42.380]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:65:29)
[08:58:42.380] info  - Generating static pages (19/19)
[08:58:42.446] error Command failed with exit code 1.
[08:58:42.446] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[08:58:42.466] Error: Command "yarn run build" exited with 1
```

**Comment by steven-tey** [comment]
It's something to do with the [static tweets render](https://github.com/steven-tey/dub/blob/main/lib/twitter/get-tweet.ts) – you can get rid of that since you won't be needing that for the link shortener

**Comment by masteradit** [comment]
> you can get rid of that

@steven-tey Should I just delete the file or do something else?
