### ISSUE TITLE
How to fix this error .

### ISSUE THREAD

**Issue by ssangyongsports** [steven-tey/dub#144]
at RequestHandler.handleRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:34310:13)
--
19:01:30 | at RequestHandler.request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:34293:12)
19:01:30 | at async PrismaClient._request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:35273:16)
19:01:30 | at async getStaticPaths (/vercel/path0/.next/server/pages/_root/[domain].js:187:21)
19:01:30 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:597:33)
19:01:30 | at async /vercel/path0/node_modules/next/dist/build/utils.js:929:115
19:01:30 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {

**Comment by steven-tey** [comment]
Closing due to inactivity.
