### ISSUE TITLE
Error serializing `.stars` returned from `getStaticProps` in "/".

### ISSUE THREAD

**Issue by xPolar** [steven-tey/dub#15]
Getting this error after trying to deploy to Vercel.
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
--
19:56:08.857 | Error: Error serializing `.stars` returned from `getStaticProps` in "/".
19:56:08.857 | Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
19:56:08.857 | at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:36:19)
19:56:08.857 | at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:43:66
19:56:08.858 | at Array.every (<anonymous>)
19:56:08.858 | at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:40:39)
19:56:08.859 | at Object.isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:63:12)
19:56:08.859 | at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:441:93)
19:56:08.859 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
19:56:08.859 | at async /vercel/path0/node_modules/next/dist/export/worker.js:304:36
19:56:08.859 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
19:56:08.860 |  
19:56:08.860 | > Build error occurred
19:56:08.860 | info  - Generating static pages (16/16)
19:56:08.863 | Error: Export encountered errors on following paths:
19:56:08.863 | /
19:56:08.863 | at /vercel/path0/node_modules/next/dist/export/index.js:404:19
19:56:08.863 | at runMicrotasks (<anonymous>)
19:56:08.864 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
19:56:08.864 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
19:56:08.864 | at async /vercel/path0/node_modules/next/dist/build/index.js:1229:21
19:56:08.864 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
19:56:08.864 | at async /vercel/path0/node_modules/next/dist/build/index.js:1091:17
19:56:08.865 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
19:56:08.865 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:65:29)
19:56:08.905 | error Command failed with exit code 1.
19:56:08.905 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:56:08.912 | Error: Command "yarn run build" exited with 1
```

**Comment by steven-tey** [comment]
Whoops, this is a silly mistake on my end (I should've accounted for the case where you don't have the `GITHUB_OAUTH_TOKEN` env var set. Feel free to set `stars` to 0 or something! 

This PR should fix it: https://github.com/steven-tey/dub/pull/16

Also added some self-hosted setup instructions in the `.env.example` file (it's not perfect yet but it's a start)
