### ISSUE TITLE
How to fix warnings and errors?

### ISSUE THREAD

**Issue by cesarlugoo** [steven-tey/dub#151]
How to fix this errors and warning while trying to connect to Prisma?

[15:15:42.816] Running build in Washington, D.C., USA (East) – iad1
[15:15:42.860] Cloning github.com/cesarlugoo/musuitesl (Branch: main, Commit: 0e5742b)
[15:15:43.186] Previous build cache not available
[15:15:43.426] Cloning completed: 565.654ms
[15:15:43.604] Running "vercel build"
[15:15:44.170] Vercel CLI 28.15.1
[15:15:44.522] Installing dependencies...
[15:15:44.897] yarn install v1.22.17
[15:15:44.986] [1/4] Resolving packages...
[15:15:45.438] [2/4] Fetching packages...
[15:16:18.870] [3/4] Linking dependencies...
[15:16:18.883] warning " > focus-trap-react@10.0.1" has unmet peer dependency "prop-types@^15.8.1".
[15:16:18.884] warning "mailing-core > mjml-react > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".
[15:16:18.885] warning "react-hot-toast > goober@2.1.11" has unmet peer dependency "csstype@^3.0.10".
[15:16:18.886] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "konva@>=2.6".
[15:16:18.887] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "react-konva@^16.8.0 || ^17.0.0".
[15:16:18.887] warning "react-spring > @react-spring/native@9.5.5" has unmet peer dependency "react-native@>=0.58".
[15:16:18.888] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "@react-three/fiber@>=6.0".
[15:16:18.888] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "three@>=0.126".
[15:16:18.888] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "react-zdog@>=1.0".
[15:16:18.889] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "zdog@>=1.0".
[15:16:18.890] warning " > @trivago/prettier-plugin-sort-imports@4.0.0" has unmet peer dependency "@vue/compiler-sfc@3.x".
[15:16:18.913] warning Workspaces can only be enabled in private projects.
[15:16:35.073] [4/4] Building fresh packages...
[15:16:44.287] $ prisma generate || true
[15:16:45.314] Prisma schema loaded from prisma/schema.prisma
[15:16:46.420] 
[15:16:46.420] ✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 295ms
[15:16:46.420] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[15:16:46.421] ```
[15:16:46.421] import { PrismaClient } from '@prisma/client'
[15:16:46.421] const prisma = new PrismaClient()
[15:16:46.421] ```
[15:16:46.493] Done in 61.60s.
[15:16:46.529] Detected Next.js version: 13.0.5
[15:16:46.532] Running "yarn run build"
[15:16:46.800] yarn run v1.22.17
[15:16:46.847] $ prisma generate
[15:16:47.875] Prisma schema loaded from prisma/schema.prisma
[15:16:48.962] 
[15:16:48.962] ✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 281ms
[15:16:48.963] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[15:16:48.963] ```
[15:16:48.963] import { PrismaClient } from '@prisma/client'
[15:16:48.963] const prisma = new PrismaClient()
[15:16:48.963] ```
[15:16:51.590] ┌─────────────────────────────────────────────────────────┐
[15:16:51.590] │  Update available 4.9.0 -> 4.10.0                       │
[15:16:51.590] │  Run the following to update                            │
[15:16:51.590] │    yarn add --dev prisma@latest                         │
[15:16:51.591] │    yarn add @prisma/client@latest                       │
[15:16:51.591] └─────────────────────────────────────────────────────────┘
[15:16:51.603] $ next build
[15:16:52.133] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[15:16:52.134] This information is used to shape Next.js' roadmap and prioritize features.
[15:16:52.134] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[15:16:52.134] https://nextjs.org/telemetry
[15:16:52.134] 
[15:16:52.293] info  - Linting and checking validity of types...
[15:17:04.613] info  - Creating an optimized production build...
[15:17:04.683] warn  - You are using an experimental edge runtime, the API might change.
[15:17:40.107] <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (177kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
[15:17:51.538] warn  - Compiled with warnings
[15:17:51.538] 
[15:17:51.539] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[15:17:51.540] A Node.js API is used (process.version at line: 26) which is not supported in the Edge Runtime.
[15:17:51.540] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[15:17:51.540] 
[15:17:51.540] Import trace for requested module:
[15:17:51.540] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[15:17:51.540] ./lib/upstash.ts
[15:17:51.541] 
[15:17:51.541] info  - Collecting page data...
[15:17:52.934] PrismaClientKnownRequestError: 
[15:17:52.935] Invalid `prisma.project.findMany()` invocation:
[15:17:52.935] 
[15:17:52.935] 
[15:17:52.936] The table `(not available)` does not exist in the current database.
[15:17:52.937]     at RequestHandler.handleRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31941:13)
[15:17:52.937]     at RequestHandler.handleAndLogRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31913:12)
[15:17:52.937]     at RequestHandler.request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31908:12)
[15:17:52.937]     at async PrismaClient._request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:32994:16)
[15:17:52.938]     at async getStaticPaths (/vercel/path0/.next/server/pages/_root/[domain].js:187:21)
[15:17:52.938]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:597:33)
[15:17:52.938]     at async /vercel/path0/node_modules/next/dist/build/utils.js:929:115
[15:17:52.939]   code: 'P2021',
[15:17:52.939]   clientVersion: '4.9.0',
[15:17:52.939]   meta: { table: '(not available)' },
[15:17:52.939]   batchRequestIdx: undefined
[15:17:52.940] }
[15:17:52.940] 
[15:17:52.940] > Build error occurred
[15:17:52.942] Error: Failed to collect page data for /_root/[domain]
[15:17:52.942]     at /vercel/path0/node_modules/next/dist/build/utils.js:959:15 {
[15:17:52.943]   type: 'Error'
[15:17:52.943] }
[15:17:53.034] error Command failed with exit code 1.
[15:17:53.034] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[15:17:53.056] Error: Command "yarn run build" exited with 1
[15:17:53.139] {
[15:17:53.139]   isVercelBuildError: true,
[15:17:53.139]   errorValue: Error: Command "yarn run build" exited with 1
[15:17:53.139]       at ChildProcess.<anonymous> (/var/task/node_modules/@vercel/build-utils/dist/index.js:31018:20)
[15:17:53.140]       at ChildProcess.emit (node:events:513:28)
[15:17:53.140]       at ChildProcess.emit (node:domain:489:12)
[15:17:53.140]       at maybeClose (node:internal/child_process:1100:16)
[15:17:53.140]       at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
[15:17:53.140]     hideStackTrace: true,
[15:17:53.140]     code: 'BUILD_UTILS_SPAWN_1',
[15:17:53.141]     printed: true
[15:17:53.141]   },
[15:17:53.141]   from: 'buildStep',
[15:17:53.141]   message: ''
[15:17:53.141] }

**Comment by steven-tey** [comment]
You'll need to generate the Prisma Schema first – run `npx prisma db push`

**Comment by dillfrescott** [comment]
It says: `The database is already in sync with the Prisma schema.`

**Comment by dillfrescott** [comment]
```
./node_modules/@upstash/redis/esm/platforms/nodejs.js
--
02:06:08.472 | A Node.js API is used (process.version at line: 26) which is not supported in the Edge Runtime.
02:06:08.472 | Learn more: https://nextjs.org/docs/api-reference/edge-runtime
02:06:08.472 |  
02:06:08.473 | Import trace for requested module:
02:06:08.473 | ./node_modules/@upstash/redis/esm/platforms/nodejs.js
02:06:08.473 | ./lib/upstash.ts
02:06:08.473 |  
02:06:08.473 | info  - Collecting page data...
02:06:09.562 | PrismaClientKnownRequestError:
02:06:09.562 | Invalid `prisma.project.findMany()` invocation:
02:06:09.562 |  
02:06:09.562 |  
02:06:09.562 | The table `(not available)` does not exist in the current database.
02:06:09.562 | at RequestHandler.handleRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31941:13)
02:06:09.563 | at RequestHandler.handleAndLogRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31913:12)
02:06:09.563 | at RequestHandler.request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31908:12)
02:06:09.563 | at async PrismaClient._request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:32994:16)
02:06:09.563 | at async getStaticPaths (/vercel/path0/.next/server/pages/_root/[domain].js:187:21)
02:06:09.563 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:597:33)
02:06:09.563 | at async /vercel/path0/node_modules/next/dist/build/utils.js:929:115
02:06:09.563 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
02:06:09.563 | code: 'P2021',
02:06:09.563 | clientVersion: '4.9.0',
02:06:09.564 | meta: { table: '(not available)' },
02:06:09.564 | batchRequestIdx: undefined
02:06:09.564 | }
02:06:09.564 |  
02:06:09.564 | > Build error occurred
02:06:09.566 | Error: Failed to collect page data for /_root/[domain]
02:06:09.567 | at /vercel/path0/node_modules/next/dist/build/utils.js:959:15 {
02:06:09.567 | type: 'Error'
02:06:09.572 | }
02:06:09.631 | error Command failed with exit code 1.
02:06:09.632 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
02:06:09.651 | Error: Command "yarn run build" exited with 1
```
