### ISSUE TITLE
Error while deploying vercel

### ISSUE THREAD

**Issue by Juijote** [steven-tey/dub#173]
```
[21:43:29.807] Running build in Washington, D.C., USA (East) – iad1
[21:43:29.873] Cloning github.com/Juijote/dub (Branch: main, Commit: 40bc999)
[21:43:30.163] Previous build cache not available
[21:43:30.472] Cloning completed: 598.951ms
[21:43:30.612] Running "vercel build"
[21:43:31.048] Vercel CLI 28.18.5
[21:43:31.318] Installing dependencies...
[21:43:31.623] yarn install v1.22.17
[21:43:31.693] [1/4] Resolving packages...
[21:43:31.992] [2/4] Fetching packages...
[21:44:04.615] [3/4] Linking dependencies...
[21:44:04.623] warning " > focus-trap-react@10.0.1" has unmet peer dependency "prop-types@^15.8.1".
[21:44:04.623] warning "mailing-core > mjml-react > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".
[21:44:04.624] warning "react-hot-toast > goober@2.1.11" has unmet peer dependency "csstype@^3.0.10".
[21:44:04.624] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "konva@>=2.6".
[21:44:04.624] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "react-konva@^16.8.0 || ^17.0.0".
[21:44:04.625] warning "react-spring > @react-spring/native@9.5.5" has unmet peer dependency "react-native@>=0.58".
[21:44:04.625] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "@react-three/fiber@>=6.0".
[21:44:04.625] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "three@>=0.126".
[21:44:04.625] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "react-zdog@>=1.0".
[21:44:04.625] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "zdog@>=1.0".
[21:44:04.626] warning " > @trivago/prettier-plugin-sort-imports@4.0.0" has unmet peer dependency "@vue/compiler-sfc@3.x".
[21:44:04.643] warning Workspaces can only be enabled in private projects.
[21:44:23.916] [4/4] Building fresh packages...
[21:44:30.497] $ prisma generate || true
[21:44:31.345] Prisma schema loaded from prisma/schema.prisma
[21:44:32.246] 
[21:44:32.247] ✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 221ms
[21:44:32.247] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[21:44:32.247] ```
[21:44:32.247] import { PrismaClient } from '@prisma/client'
[21:44:32.247] const prisma = new PrismaClient()
[21:44:32.247] ```
[21:44:32.298] Done in 60.68s.
[21:44:32.330] Detected Next.js version: 13.2.4
[21:44:32.333] Running "yarn run build"
[21:44:32.500] yarn run v1.22.17
[21:44:32.531] $ prisma generate
[21:44:33.337] Prisma schema loaded from prisma/schema.prisma
[21:44:34.237] 
[21:44:34.238] ✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 225ms
[21:44:34.238] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[21:44:34.238] ```
[21:44:34.238] import { PrismaClient } from '@prisma/client'
[21:44:34.238] const prisma = new PrismaClient()
[21:44:34.238] ```
[21:44:34.353] ┌─────────────────────────────────────────────────────────┐
[21:44:34.353] │  Update available 4.9.0 -> 4.12.0                       │
[21:44:34.353] │  Run the following to update                            │
[21:44:34.353] │    yarn add --dev prisma@latest                         │
[21:44:34.354] │    yarn add @prisma/client@latest                       │
[21:44:34.354] └─────────────────────────────────────────────────────────┘
[21:44:34.367] $ next build
[21:44:34.865] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[21:44:34.865] This information is used to shape Next.js' roadmap and prioritize features.
[21:44:34.865] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[21:44:34.865] https://nextjs.org/telemetry
[21:44:34.866] 
[21:44:34.997] info  - Linting and checking validity of types...
[21:44:44.116] info  - Creating an optimized production build...
[21:44:44.163] warn  - You are using an experimental edge runtime, the API might change.
[21:45:15.474] <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (177kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
[21:45:24.370] warn  - Compiled with warnings
[21:45:24.371] 
[21:45:24.371] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[21:45:24.371] A Node.js API is used (process.version at line: 26) which is not supported in the Edge Runtime.
[21:45:24.371] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[21:45:24.371] 
[21:45:24.371] Import trace for requested module:
[21:45:24.371] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[21:45:24.372] ./lib/upstash.ts
[21:45:24.372] 
[21:45:24.375] info  - Collecting page data...
[21:45:31.790] info  - Generating static pages (0/16)
[21:45:31.914] info  - Generating static pages (4/16)
[21:45:31.947] info  - Generating static pages (8/16)
[21:45:32.042] info  - Generating static pages (12/16)
[21:45:32.132] TypeError: Cannot read properties of null (reading 'id')
[21:45:32.133]     at /vercel/path0/.next/server/pages/metatags.js:225:38
[21:45:32.133]     at Array.map (<anonymous>)
[21:45:32.133]     at Metatags (/vercel/path0/.next/server/pages/metatags.js:223:42)
[21:45:32.133]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[21:45:32.134]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[21:45:32.134]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[21:45:32.134]     at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[21:45:32.134]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[21:45:32.134]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[21:45:32.134]     at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[21:45:32.134] 
[21:45:32.134] Error occurred prerendering page "/metatags". Read more: https://nextjs.org/docs/messages/prerender-error
[21:45:32.134] TypeError: Cannot read properties of null (reading 'id')
[21:45:32.134]     at /vercel/path0/.next/server/pages/metatags.js:225:38
[21:45:32.135]     at Array.map (<anonymous>)
[21:45:32.135]     at Metatags (/vercel/path0/.next/server/pages/metatags.js:223:42)
[21:45:32.135]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[21:45:32.135]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[21:45:32.135]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[21:45:32.135]     at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[21:45:32.135]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[21:45:32.135]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[21:45:32.135]     at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[21:45:32.799] info  - Generating static pages (16/16)
[21:45:32.801] 
[21:45:32.801] > Build error occurred
[21:45:32.804] Error: Export encountered errors on following paths:
[21:45:32.804] 	/metatags
[21:45:32.804]     at /vercel/path0/node_modules/next/dist/export/index.js:425:19
[21:45:32.804]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[21:45:32.804]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[21:45:32.804]     at async /vercel/path0/node_modules/next/dist/build/index.js:1422:21
[21:45:32.804]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[21:45:32.804]     at async /vercel/path0/node_modules/next/dist/build/index.js:1280:17
[21:45:32.804]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[21:45:32.804]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:73:29)
[21:45:32.864] error Command failed with exit code 1.
[21:45:32.864] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[21:45:32.881] Error: Command "yarn run build" exited with 1
[21:45:33.572] Deployment completed
[21:45:33.134] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

**Comment by steven-tey** [comment]
This should've been fixed with https://github.com/steven-tey/dub/pull/178 – sorry about that!
