### ISSUE TITLE
Is that any way to self host using docker?

### ISSUE THREAD

**Issue by BhautikChudasama** [steven-tey/dub#25]
Is that any way (or future) plan for hosting using docker?

**Comment by steven-tey** [comment]
Seems like a lot of folks are interested in this: https://github.com/steven-tey/dub/issues/12

To be completely honest I'm not very familiar with docker – if someone can PR this option into a branch (i.e. `docker`) I'm more than happy to feature it in the README as one of the self-hosted options :)

**Comment by BhautikChudasama** [comment]
Can you specify environment variables needed to run / What services must run in order to run dub.sh?

**Comment by BhautikChudasama** [comment]
Got it from .env.example.

**Comment by ruanbekker** [comment]
Im busy with adding a self-host option with docker in a wip branch:
- https://github.com/ruanbekker/dub/tree/docker

```bash
docker-compose up -d --build
```

Then access in port 3000:

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/567298/192400685-49f6a7ea-ecca-4cf0-82f2-798833a1e754.png">

Atm getting a error:

```
dub-app      | Error [TypeError]: fetch failed
dub-app      |     at Object.processResponse (evalmachine.<anonymous>:3163:27)
dub-app      |     at <unknown> (evalmachine.<anonymous>:3507:42)
dub-app      |     at <unknown> (internal/process/task_queues.js:141:7)
dub-app      |     at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
dub-app      |     at AsyncResource.runMicrotask (internal/process/task_queues.js:138:8)
```

This might perhaps be due to the use of Upstash. Will look into it tomorrow again

**Comment by steven-tey** [comment]
Just wanted to follow up and say that I haven't forgotten about this issue yet – it's top on my TODO list for this week! Sorry again for the delay 😅

**Comment by IzMichael** [comment]
Is this still in the cards, or not a high priority atm?

**Comment by ps-89** [comment]
I can help with the docker setup, I've started with a self hosted setup on vercel. Have been able to sort out all issues. Just that how do I set the `app.DOMAIN.vercel.app` to point to dub.sh? 

@steven-tey any idea on this?

**Comment by steven-tey** [comment]
@IzMichael yes it's definitely still in the cards, apologies for the delay, I was busy with Next.js Conf + a few other updates for Dub the last couple of weeks. Will get to this as soon as I can!

@ps-89 we'll probably need to turn all instances of `dub.sh` into a modular `process.env.MAIN_DOMAIN`, which should be possible by doing a search and replace all inside VSCode!

**Comment by ps-89** [comment]
@steven-tey I can raise a PR for this if you want(will help other folks with self set up)

Also, any plans to have a community slack/discord?

**Comment by steven-tey** [comment]
That would be amazing – I'm also trying to think of a way to modularize away all the unnecessary stuff (e.g. landing page, Stripe integration), if y'all have any ideas I'm all ears! One way to do this is with [Next.js 13's route groups](https://beta.nextjs.org/docs/routing/defining-routes#route-groups) 👀

As for community Slack/Discord, I'm thinking of trying out [Threads](http://threads.com/) instead, but might stick to Discord depending if it works out well with an OSS model. Will keep y'all posted!

**Comment by ps-89** [comment]
@steven-tey Sure will raise a couple of PRs to start fixing a few things. I make a fork and made it run on vercel but that required quite a few tweaks here and there. Will raise a PR to merge it into this repo.

We can try threads or slack or discord, whatever folks have a low barrier to entry and less context switch in using. Also, whichever is free and/or cheap. Primary reason is to ideate over a comms platform and perhaps fix few issues us(and others) are or might be facing. Let's set it up.

**Comment by steven-tey** [comment]
@ps-89 here you go: https://dub.sh/slack

It's by no means polished yet but feel free to join! :)

**Comment by ps-89** [comment]
@steven-tey I guess it needs elegance.co email.

```
Don’t have an @elegance.co email address?
Contact the workspace administrator at Dub for an invitation.
```

I've DMed you my email for slack on your twitter.

**Comment by steven-tey** [comment]
@ps-89 Oh weird, sorry about that! I just updated the link – can you try again?=

**Comment by ItsJamesMurray** [comment]
Any update here? I'd love to self-host but prefer everything through docker and running on my home-lab.

**Comment by Ashutosh-Malve** [comment]
Any update here? [steven-tey](https://github.com/steven-tey)

**Comment by Stunt0265** [comment]
I'm interested in self-host docker as well.

**Comment by R7JANV1** [comment]
+1

**Comment by ralyodio** [comment]
any movemenet on this? its been over a year. dub.sh looks cool but I'd like docker-compose.yml support.

**Comment by hexclann** [comment]
+1

**Comment by cirrusflyer** [comment]
Docker would be perfect.

**Comment by steven-tey** [comment]
Quickly following up here – we don't have any plans to add official Docker support for Dub, but we're more than happy to accept community contributions! 

It'll look something like @calcom's community-maintained Docker support: https://cal.com/docs/introduction/quick-start/self-hosting/docker

**Comment by cirrusflyer** [comment]
Can I ask why you won't support Docker officially?

**Comment by 0x7466** [comment]
+1

**Comment by ARHAEEM** [comment]
I beleive the best ever option here is to make docker installation with coolify.io. 

They already suggested it there and i beleive they will integrate it soon.

Coolify is another amazing docker mangament Panel. adding the integration as template will give users for both projects win=win

**Comment by luolongfei** [comment]
+1

**Comment by SutanuNandigrami** [comment]
Whats the point of open source if you don't support docker to self host? just for free development and then charge subscriptions?

**Comment by amirakrari** [comment]
> Lets now stop making comments that provide zero value.

This is not zero value. would like to stay updated on the progres. is it in the roadmap? good luck with dub it seems to be an amazing tool.
edit: edited the message was a bit rude.

**Comment by MatthiasLubbertsen** [comment]
is this still on the roadmap? dub seems to be a amazing tool with a great ui, and would love to self host this. :eyes:

**Comment by ARHAEEM** [comment]
They didn’t want to support Docker because people would avoid using their super-expensive hosting providers that they partner with. that's all.

**Comment by thanhtoan1196** [comment]
any updates?
