### ISSUE TITLE
[Need help] Missing api key

### ISSUE THREAD

**Issue by Guangsudalao** [steven-tey/dub#282]
I tried to delete the /metatags folder, but an error still occurred. I don't know why this problem occurred, I can't find any issues about this error. I need help.
Here's vercel's deployment log.
~~~
[07:49:46.480] Running build in San Francisco, USA (West) – sfo1
[07:49:46.543] Cloning github.com/Guangsudalao/dub (Branch: main, Commit: 669fbe4)
[07:49:46.674] Previous build cache not available
[07:49:47.556] Cloning completed: 1.013s
[07:49:47.770] Running "vercel build"
[07:49:48.286] Vercel CLI 31.0.4
[07:49:48.573] Installing dependencies...
[07:49:48.861] yarn install v1.22.17
[07:49:48.941] [1/4] Resolving packages...
[07:49:49.317] [2/4] Fetching packages...
[07:50:28.560] [3/4] Linking dependencies...
[07:50:28.579] warning " > focus-trap-react@10.0.1" has unmet peer dependency "prop-types@^15.8.1".
[07:50:28.581] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "konva@>=2.6".
[07:50:28.581] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "react-konva@^16.8.0 || ^17.0.0".
[07:50:28.581] warning "react-spring > @react-spring/native@9.5.5" has unmet peer dependency "react-native@>=0.58".
[07:50:28.582] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "@react-three/fiber@>=6.0".
[07:50:28.582] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "three@>=0.126".
[07:50:28.585] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "react-zdog@>=1.0".
[07:50:28.585] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "zdog@>=1.0".
[07:50:28.585] warning " > @trivago/prettier-plugin-sort-imports@4.0.0" has unmet peer dependency "@vue/compiler-sfc@3.x".
[07:50:28.616] warning Workspaces can only be enabled in private projects.
[07:50:28.616] warning Workspaces can only be enabled in private projects.
[07:50:28.656] warning Workspaces can only be enabled in private projects.
[07:50:28.660] warning Workspaces can only be enabled in private projects.
[07:50:28.684] warning Workspaces can only be enabled in private projects.
[07:50:28.684] warning Workspaces can only be enabled in private projects.
[07:51:00.105] [4/4] Building fresh packages...
[07:51:04.056] Done in 75.20s.
[07:51:04.165] Detected Next.js version: 13.4.10-canary.3
[07:51:04.167] Running "yarn run build"
[07:51:04.374] yarn run v1.22.17
[07:51:04.406] $ prisma generate & next build
[07:51:04.995] - warn You have enabled experimental features (useDeploymentId, serverActions, useDeploymentIdServerActions) in next.config.js.
[07:51:04.995] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[07:51:04.996] 
[07:51:05.010] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[07:51:05.011] This information is used to shape Next.js' roadmap and prioritize features.
[07:51:05.011] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[07:51:05.011] https://nextjs.org/telemetry
[07:51:05.011] 
[07:51:05.108] - info Creating an optimized production build...
[07:51:05.227] Prisma schema loaded from prisma/schema.prisma
[07:51:06.223] 
[07:51:06.223] ✔ Generated Prisma Client (4.13.0 | library) to ./node_modules/@prisma/client in 292ms
[07:51:06.224] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[07:51:06.224] ```
[07:51:06.224] import { PrismaClient } from '@prisma/client'
[07:51:06.225] const prisma = new PrismaClient()
[07:51:06.225] ```
[07:51:08.897] Generated 29 documents in .contentlayer
[07:52:24.861] <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (830kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
[07:52:55.062] - warn Compiled with warnings
[07:52:55.062] 
[07:52:55.062] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[07:52:55.062] A Node.js API is used (process.version at line: 40) which is not supported in the Edge Runtime.
[07:52:55.062] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[07:52:55.062] 
[07:52:55.062] Import trace for requested module:
[07:52:55.062] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[07:52:55.062] ./lib/upstash.ts
[07:52:55.062] 
[07:52:55.063] - info Linting and checking validity of types...
[07:53:09.895] - info Collecting page data...
[07:53:11.491] Error: Missing API key. Pass it to the constructor `new Resend("re_123")`
[07:53:11.491]     at new Resend (/vercel/path0/.next/server/chunks/5780.js:34078:23)
[07:53:11.491]     at 79327 (/vercel/path0/.next/server/app/api/cron/import/route.js:160:16)
[07:53:11.491]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[07:53:11.497]     at __webpack_exec__ (/vercel/path0/.next/server/app/api/cron/import/route.js:713:39)
[07:53:11.497]     at /vercel/path0/.next/server/app/api/cron/import/route.js:714:120
[07:53:11.497]     at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:230:21)
[07:53:11.497]     at /vercel/path0/.next/server/app/api/cron/import/route.js:714:47
[07:53:11.497]     at Object.<anonymous> (/vercel/path0/.next/server/app/api/cron/import/route.js:717:3)
[07:53:11.498]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[07:53:11.504]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[07:53:11.504] 
[07:53:11.504] > Build error occurred
[07:53:11.505] Error: Failed to collect page data for /api/cron/import
[07:53:11.505]     at /vercel/path0/node_modules/next/dist/build/utils.js:1157:15
[07:53:11.505]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[07:53:11.505]   type: 'Error'
[07:53:11.505] }
[07:53:11.723] error Command failed with exit code 1.
[07:53:11.723] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[07:53:11.754] Error: Command "yarn run build" exited with 1
~~~

**Comment by steven-tey** [comment]
You need a [Resend](https://resend.com/) API key to send emails!

Closing this now as it's related to #12
