### ISSUE TITLE
The table `(not available)` does not exist in the current database

### ISSUE THREAD

**Issue by ictcentervnn** [steven-tey/dub#340]
[15:40:48.217] PrismaClientKnownRequestError: 
[15:40:48.217] Invalid `prisma.domain.findMany()` invocation:
[15:40:48.218] 
[15:40:48.218] 
[15:40:48.218] The table `(not available)` does not exist in the current database.
[15:40:48.218]     at vn.handleRequestError (/vercel/path0/node_modules/@prisma/client/runtime/library.js:123:6730)
[15:40:48.218]     at vn.handleAndLogRequestError (/vercel/path0/node_modules/@prisma/client/runtime/library.js:123:6119)
[15:40:48.219]     at vn.request (/vercel/path0/node_modules/@prisma/client/runtime/library.js:123:5839)
[15:40:48.219]     at async l (/vercel/path0/node_modules/@prisma/client/runtime/library.js:128:9763)
[15:40:48.219]     at async Object.generateStaticParams (/vercel/path0/.next/server/app/[domain]/page.js:738:63)
[15:40:48.219]     at async buildParams (/vercel/path0/node_modules/next/dist/build/utils.js:925:36)
[15:40:48.220]     at async /vercel/path0/node_modules/next/dist/build/utils.js:942:33
[15:40:48.220]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1075:117
[15:40:48.220]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:105:20) {
[15:40:48.220]   code: 'P2021',
[15:40:48.221]   clientVersion: '5.2.0',
[15:40:48.221]   meta: { table: '(not available)' }
[15:40:48.221] }
[15:40:48.221] 
[15:40:48.221] > Build error occurred
[15:40:48.222] Error: Failed to collect page data for /[domain]
[15:40:48.222]     at /vercel/path0/node_modules/next/dist/build/utils.js:1164:15 {
[15:40:48.222]   type: 'Error'
[15:40:48.222] }
[15:40:48.399] error Command failed with exit code 1.
[15:40:48.399] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[15:40:48.432] Error: Command "yarn run build" exited with 1

**Comment by steven-tey** [comment]
You'll need to run `npx prisma db push` first to initiate the database
