### ISSUE TITLE
`ERR_INVALID_URL` error when running yarn run build locally. I've setup the .env file with all the values correctly

### ISSUE THREAD

**Issue by ps-89** [steven-tey/dub#99]
```
warn  - You are using an experimental edge runtime, the API might change.
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data ..TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at parseUrl (/Users/test/dub.sh/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/dub.sh/node_modules/next-auth/react/index.js:70:34)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  input: '',
  code: 'ERR_INVALID_URL'
}

> Build error occurred
Error: Failed to collect page data for /_auth/[domain]/[key]
    at /Users/test/dub.sh/node_modules/next/dist/build/utils.js:916:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'Error'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ps-89** [comment]
Also just wanted to ask if there's any discord community or any other comms platform that dub.sh uses that we can use for questions about architecture and set up(self hosting)?

**Comment by ps-89** [comment]
Was able to fix the above error by providing the value of `NEXT_AUTH_URL`, even though it's mentioned in their code(next-auth's codebase) that it picks localhost:3000 as default value, this env variable has to be there.

```
NEXTAUTH_URL=http://localhost:3000
```

I'm getting a new error now:

```
info  - Compiled successfully
info  - Collecting page data
[  ==] info  - Generating static pages (16/17)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'entities')
    at getExternalUrls (/Users/test/dub-notion/dub.sh/.next/server/pages/index.js:2137:36)
    at getTweet (/Users/test/dub-notion/dub.sh/.next/server/pages/index.js:2150:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async getStaticProps (/Users/test/dub-notion/dub.sh/.next/server/pages/index.js:2297:20)
    at async renderToHTML (/Users/test/dub-notion/dub.sh/node_modules/next/dist/server/render.js:386:20)
    at async /Users/test/dub-notion/dub.sh/node_modules/next/dist/export/worker.js:304:36
    at async Span.traceAsyncFn (/Users/test/dub-notion/dub.sh/node_modules/next/dist/trace/trace.js:79:20)
info  - Generating static pages (17/17)

> Build error occurred
Error: Export encountered errors on following paths:
	/
    at /Users/test/dub-notion/dub.sh/node_modules/next/dist/export/index.js:404:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/test/dub-notion/dub.sh/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/test/dub-notion/dub.sh/node_modules/next/dist/build/index.js:1229:21
    at async Span.traceAsyncFn (/Users/test/dub-notion/dub.sh/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/test/dub-notion/dub.sh/node_modules/next/dist/build/index.js:1091:17
    at async Span.traceAsyncFn (/Users/test/dub-notion/dub.sh/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/Users/test/dub-notion/dub.sh/node_modules/next/dist/build/index.js:65:29)
error Command failed with exit code 1.
```

**Comment by ps-89** [comment]
Was able to fix the above error by providing the value of `NEXT_AUTH_URL`, even though it's mentioned in their code(next-auth's codebase) that it picks localhost:3000 as default value, this env variable has to be there.

```
NEXTAUTH_URL=http://localhost:3000
```

I'm getting a new error now:

```
info  - Compiled successfully
info  - Collecting page data
[  ==] info  - Generating static pages (16/17)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'entities')
    at getExternalUrls (/Users/test/dub.sh/.next/server/pages/index.js:2137:36)
    at getTweet (/Users/test/dub.sh/.next/server/pages/index.js:2150:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async getStaticProps (/Users/test/dub.sh/.next/server/pages/index.js:2297:20)
    at async renderToHTML (/Users/test/dub.sh/node_modules/next/dist/server/render.js:386:20)
    at async /Users/test/dub.sh/node_modules/next/dist/export/worker.js:304:36
    at async Span.traceAsyncFn (/Users/test/dub.sh/node_modules/next/dist/trace/trace.js:79:20)
info  - Generating static pages (17/17)

> Build error occurred
Error: Export encountered errors on following paths:
	/
    at /Users/test/dub.sh/node_modules/next/dist/export/index.js:404:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/test/dub.sh/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/test/dub.sh/node_modules/next/dist/build/index.js:1229:21
    at async Span.traceAsyncFn (/Users/test/dub.sh/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/test/dub.sh/node_modules/next/dist/build/index.js:1091:17
    at async Span.traceAsyncFn (/Users/test/dub.sh/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/Users/test/dub.sh/node_modules/next/dist/build/index.js:65:29)
error Command failed with exit code 1.
```

**Comment by ps-89** [comment]
Closing this as I had resolved this. Happy to help out others, feel free to tag me in this thread.
